config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'words#index'
  resources :words
  resources :games, only: %i[new create show]
  resources :answers, only: %i[create]
end

app/models/application_record.rb
# frozen_string_literal: true

# Application Record
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user

  def correctness
    return '-' if total_answers_count.zero?
    value = (good_answer_count.to_f / total_answers_count) * 100
    value = value.round(2)
    value.to_s + '%'
  end

  private

  def total_answers_count
    good_answer_count + bad_answer_count
  end
end

app/models/language.rb
# frozen_string_literal: true

# word Active Model
class Language < ApplicationRecord
  has_many :words
  validates :name, presence: true
  validates :name, inclusion: { in: LanguageList::COMMON_LANGUAGES.map(&:name) }
end

app/models/translation.rb
class Translation < ApplicationRecord
  belongs_to :word
  belongs_to :translated_word, class_name: 'Word'
end

app/models/user.rb
# frozen_string_literal: true

# User model
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :words
  has_many :games

  def secret_email
    email.gsub(/.{0,4}@/, '####@')
  end    
end

app/models/word.rb
# frozen_string_literal: true

# word Active Model
class Word < ApplicationRecord
  belongs_to :language
  belongs_to :user

  has_many :translations_association, class_name: 'Translation'
  has_many :translations, through: :translations_association, source: :translated_word
  has_many :inverse_translations_association, class_name: 'Translation', foreign_key: 'translated_word_id'
  has_many :inverse_translations, through: :inverse_translations_association, source: :word

  validates :content, :language, presence: true
  validate :translation_language_cannot_same_as_word_language
  accepts_nested_attributes_for :translations, allow_destroy: true

  paginates_per 10

  def translation_language_cannot_same_as_word_language
    return if translations.none? { |translation| translation.language == language }
    errors.add(:language, 'must be different from translation language')
  end
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

# AnswersController
class AnswersController < ApplicationController
  before_action :authenticate_user!, only: %i[create]

  def create
    authorize(game, :access?)
    checker = Words::CheckAnswer.new(word, game, answer)
    @checker = checker.call
    respond_to do |format|
      format.js
    end
  end

  private

  def word
    Word.find(params[:answer][:word_id])
  end

  def answer
    params[:answer][:content]
  end

  def game
    Game.find(params[:answer][:game_id])
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = 'You are not authorized to perform this action.'
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/games_controller.rb
# frozen_string_literal: true

# Games Conteoller
class GamesController < ApplicationController
  # before_action :set_game, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[show create]

  def index
    
  end

  def create
    game = current_user.games.create
    redirect_to(game)
  end

  def show
    @game = Game.find(params[:id])
    authorize @game
    @word = Words::RandomWord.new.call
  end
end  

app/controllers/words_controller.rb
# frozen_string_literal: true

# WordsController
class WordsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update destroy]
  before_action :set_word, only: %i[show edit update destroy]

  def index
    @words = Word.includes(:user, :language, :translations).page(params[:page])
  end

  def new
    @word = current_user.words.new
    @word.translations.new
  end

  def create
    @word = Word.new(word_params)
    @word.user = current_user
    set_user_for_translations(@word)
    if @word.save
      redirect_to(words_path)
    else
      render :new
    end
  end

  def show; end

  def edit
    authorize @word
  end

  def update
    @word = Word.find(params[:id])
    authorize @word
    @word.assign_attributes(word_params)
    set_user_for_translations(@word)
    if @word.save
      redirect_to(word_path(@word))
    else
      render :edit
    end
  end

  def destroy
    authorize @word
    @word.destroy
    redirect_to(words_path)
  end

  private

  def word_params
    params
      .require(:word)
      .permit(
        :content,
        :language_id,
        translations_attributes: %i[id content language_id _destroy]
      )
  end

  def set_word
    @word = Word.find(params[:id])
  end

  def set_user_for_translations(word)
    word.translations.each do |translation|
      translation.user = current_user
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Application helper module
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    {
      success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
    }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)}", role: "alert") do
        concat(content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' }))
        concat(message)
      end)
    end
    nil
  end
end

app/views/answers/create.js.erb
<% if @checker == true %>
  $('#answer_content').addClass('bg-success');
<% else %>
  $('#answer_content').addClass('bg-danger');
<% end %>
setTimeout(function(){ location.reload();; }, 1000);

app/views/games/show.html.haml
.jumbotron.text-center
  %h1.display-4= @word.content
  .row
    .col-md-4.offset-md-4
      = simple_form_for :answer, url: answers_path, method: :post, remote: true do |f|
        = f.input :content, as: :string, label: false, input_html: { autocomplete: 'off', autofocus: true }
        = f.input :word_id, as: :hidden, input_html: { value: @word.id }
        = f.input :game_id, as: :hidden, input_html: { value: @game.id }
        = f.submit 'Check answer', class: 'btn btn-primary btn-lg'
  %p
    %table.table
      %thead
        %tr
          %th.table-success Good Answers
          %th.table-danger Bad Answers
          %th Correctness
      %tbody
        %tr
          %td.table-success= @game.good_answer_count
          %td.table-danger= @game.bad_answer_count
          %td= @game.correctness

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RailsApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container.mt-2
      = render 'shared/navbar'
      = render 'shared/messages'
      .container-fluid
        .row
          .col-md-12.mt-2
            = yield

app/views/shared/_messages.html.haml
.container-fluid
  .row
    .col-md-12.mt-3
      = flash_messages

app/views/shared/_navbar.html.haml
.container-fluid
  .row
    .col-md-12
      %nav.navbar.navbar-expand-lg.navbar-light.bg-light
        %a.navbar-brand{href: root_path} RailsApp
        #navbarNavAltMarkup.collapse.navbar-collapse
          .navbar-nav
            - if user_signed_in?
              %li.nav-item
                = link_to('New word', new_word_path, class: 'nav-link')
              - if current_user.games.present?
                %li.nav-item
                  = link_to('Continue game', game_path(current_user.games.last), class: 'nav-link')
              - else
                %li.nav-item
                  = link_to('Start new game', games_path, method: :post, class: 'nav-link')
            - if user_signed_in?
              %li.nav-item
                = link_to('Edit registration', edit_user_registration_path, class: 'nav-link')
            - else
              %li.nav-item
                = link_to('Register', new_user_registration_path, class: 'nav-link')
            - if user_signed_in?
              %li.nav-item
                = link_to('Logout', destroy_user_session_path, class: 'nav-link', method: :delete)
            - else
              %li.nav-item
                = link_to('Login', new_user_session_path, class: 'nav-link')

app/views/shared/_navs.html.haml
.container-fluid
  .row
    .col-md-12
      %ul.nav.nav-pills
        %li.nav-item
          = link_to('Home', words_path, class: 'nav-link active')
        %li.nav-item
          = link_to('New Word', new_word_path, class: 'nav-link')
        - if user_signed_in?
          %li.nav-item
            = link_to('Edit Registration', edit_user_registration_path, class: 'nav-link')
          %li.nav-item
            = link_to('Logout', destroy_user_session_path, method: :delete, class: 'nav-link')
        - else
          %li.nav-item
            = link_to('Register', new_user_registration_path, class: 'nav-link')  
          %li.nav-item
            = link_to('Login', new_user_session_path, class: 'nav-link')

app/views/words/_form.html.haml
.row
  .col-md-6
    = simple_nested_form_for @word do |f|
      = f.input :content
      = f.association :language
      %h3 Translations
      = f.fields_for :translations do |t|
        = t.input :content
        = t.association :language
        %p= t.link_to_remove('Remove this translation', class: 'btn btn-danger')
      %p= f.link_to_add('Add a new translation', :translations, class: 'btn btn-primary')

      = f.button :submit, class: 'btn btn-primary'

app/views/words/edit.html.haml
%h1 Edit Word
= render 'form'

app/views/words/index.html.haml
%h1 All words
%table.table
  %thead
    %tr
      %th
        \#
      %th
        Content
      %th
        Language
      %th
        User
      %th
        Translations Count
      %th
        Actions
  %tbody
    - @words.each do |word|
      %tr
        %td
          = word.id
        %td
          = word.content
        %td
          = word.language.name
        %td
          = word.user.secret_email
        %td
          = word.translations.size
        %td
          = link_to('Show', word_path(word), class: 'btn btn-primary')
          - if policy(word).edit?
            = link_to('Edit', edit_word_path(word), class: 'btn btn-primary')
          - if policy(word).destroy?
            = link_to('Delete',
              word_path(word),
              class: 'btn btn-primary',
              method: :delete, data: { confirm: 'Are you sure?' })
= paginate @words, theme: 'twitter-bootstrap-4'

app/views/words/new.html.haml
%h1 New Word
= render 'form'

app/views/words/show.html.haml
%h1= @word.content
%p
  Language:
  = @word.language.name

- if @word.translations.any?
  %p
    Translations:
    = @word.translations.pluck(:content).join(', ')